# Generated by Django 4.1.7 on 2023-03-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='isSubscribed',
            field=models.BooleanField(default=True),
        ),
    ]
