# Generated by Django 4.1.7 on 2023-03-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_subscription_issubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer_key',
            field=models.CharField(default='h', max_length=100),
            preserve_default=False,
        ),
    ]
