# Generated by Django 4.1.7 on 2023-03-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0003_subscription_customer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
    ]
